<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Foros de discusin</name>
   <tag></tag>
   <elementGuidId>d45d7876-356a-4ef8-8ac7-ad4b3818d1f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac6b9648-b561-46ad-bc23-c55a1f8a88ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>d5e33d17-f290-4422-b04f-9adf34e3af6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/s/forums</value>
      <webElementGuid>13fce105-bdda-4eab-af31-e7a2d668607b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comm-navigation__top-level-item-link js-top-level-menu-item linkBtn</value>
      <webElementGuid>e49ff5f3-610f-4152-9e39-3e4e69f22a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>20:74;a</value>
      <webElementGuid>66b726ab-71c0-406e-b6a3-c3499f1586b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Foros de discusión</value>
      <webElementGuid>4f0881d0-0097-41b0-9e2b-fec0e5dede2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)</value>
      <webElementGuid>435e497b-7033-4c1b-a8f7-1c3158b69f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='3']</value>
      <webElementGuid>9c4af005-9451-47d2-a0b2-0ff8c39110d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='commThemeNav']/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>cf8d1cb6-2cbc-411b-8077-debfa05e427e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Foros de discusión')]</value>
      <webElementGuid>8c9ea9c7-f6a3-4b73-be66-2fdae946ab4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Aplicaciones'])[1]/following::a[1]</value>
      <webElementGuid>f7a9eb3a-2965-4a65-ba68-c3e30bd57172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APIs'])[1]/following::a[2]</value>
      <webElementGuid>d0dfd151-528f-414e-9bd7-89db5fe8cf49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/preceding::a[1]</value>
      <webElementGuid>6bcf8b78-6011-4bb0-96f5-9752cde814d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notifications'])[1]/preceding::a[1]</value>
      <webElementGuid>c720e647-9f0c-4873-a6ca-1ed1394c329d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Foros de discusión']/parent::*</value>
      <webElementGuid>d4bb76f6-35c7-4d88-938a-1369782c518b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/s/forums')]</value>
      <webElementGuid>c193411c-da2c-40df-a57d-81c6260dd4f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>f3a0e1b2-8831-4920-b4ae-27f332c6c2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = '3' and @href = '/s/forums' and (text() = 'Foros de discusión' or . = 'Foros de discusión')]</value>
      <webElementGuid>c030ee3b-d34b-418d-9455-6807b891334f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
