<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actualizar Informacin</name>
   <tag></tag>
   <elementGuidId>00504a85-0b7d-40b2-88a0-f819aa03e53d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.is-cuenta-menu > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountMenu-Login']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35f6ccc6-8d67-46a3-b50a-24cb992cfff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Mi_Cuenta/UpdateUser?hash=bGlzc2V5bWFtb3JhbGVzQGdtYWlsLmNvbQ==</value>
      <webElementGuid>da49a322-5962-4033-a63a-560b3a6430c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar Información</value>
      <webElementGuid>52da493c-1f55-46ea-9384-c8e227123472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountMenu-Login&quot;)/div[@class=&quot;is-cuenta-menu&quot;]/a[1]</value>
      <webElementGuid>e3c97407-8645-4088-a10f-7d5b557d5f43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountMenu-Login']/div/a</value>
      <webElementGuid>86cd7d6f-5945-4350-8da3-76033f630a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Actualizar Información')]</value>
      <webElementGuid>6caca61f-c290-4d10-82d8-7d6b35cc6084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAVE C2P'])[1]/following::a[2]</value>
      <webElementGuid>d37dda09-502b-49c4-8dfd-0ff9cb9195b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOCIONES Y PRECIOS'])[1]/following::a[3]</value>
      <webElementGuid>a3393f69-15f9-45be-8cc3-66554f436166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[1]/preceding::a[1]</value>
      <webElementGuid>f6a30e4b-9984-4c47-9011-0890a0a99fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finalizar Sesión'])[1]/preceding::a[3]</value>
      <webElementGuid>ccc409fb-d08b-451b-ba28-fc0840b9c21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actualizar Información']/parent::*</value>
      <webElementGuid>d3751e57-ac8e-43d5-8ee9-149b825783f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Mi_Cuenta/UpdateUser?hash=bGlzc2V5bWFtb3JhbGVzQGdtYWlsLmNvbQ==')]</value>
      <webElementGuid>47096fb7-b841-4127-a1cd-fca3e2bfb8c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>35becd54-a75b-4e9c-b641-120973837a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Mi_Cuenta/UpdateUser?hash=bGlzc2V5bWFtb3JhbGVzQGdtYWlsLmNvbQ==' and (text() = 'Actualizar Información' or . = 'Actualizar Información')]</value>
      <webElementGuid>5e05d8a5-9419-4ac5-acd3-e72a6726fe7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
