<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTRASEA</name>
   <tag></tag>
   <elementGuidId>6935763b-8507-435d-a878-b6be2daf9ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabs-790603']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c864f528-a415-466b-903a-140611a2106b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#panel-8948</value>
      <webElementGuid>dc27206e-0983-4545-b741-3321215ab405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>106a8d67-883b-476d-b122-cb9745ffad2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTRASEÑA</value>
      <webElementGuid>f8ed845d-04e5-4ace-a6de-7fba4ad14f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-790603&quot;)/ul[@class=&quot;nav nav-tabs&quot;]/li[3]/a[1]</value>
      <webElementGuid>19306fc5-8f73-4beb-8f0f-50d22157bc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-790603']/ul/li[3]/a</value>
      <webElementGuid>cc111377-960e-4001-b86a-33ac63d028e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CONTRASEÑA')]</value>
      <webElementGuid>21023115-fce7-43c9-a50e-330dbd61a3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATOS PERSONALES'])[1]/following::a[1]</value>
      <webElementGuid>581a7991-4c3c-4d0d-be4b-22f37c4fcf3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATOS DE REGISTRO'])[1]/following::a[2]</value>
      <webElementGuid>17ce0962-5ae0-443b-854c-ee564eea6f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFICACIONES'])[1]/preceding::a[1]</value>
      <webElementGuid>e9356557-74d3-4e86-b042-83140eac9261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATOS DE REGISTRO'])[2]/preceding::a[2]</value>
      <webElementGuid>a9a4632d-6fba-4bd0-b62c-ca820307961d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTRASEÑA']/parent::*</value>
      <webElementGuid>11369776-a332-44b5-a0d0-60a542da3816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#panel-8948')]</value>
      <webElementGuid>68a0c150-8077-48bb-b33c-22a249459082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/a</value>
      <webElementGuid>bbbff164-3a8e-4b5f-bf7f-f999726c9bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#panel-8948' and (text() = 'CONTRASEÑA' or . = 'CONTRASEÑA')]</value>
      <webElementGuid>2c57910c-25c9-42ff-9bb5-eaad58dc9386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
