<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MI CUENTA</name>
   <tag></tag>
   <elementGuidId>33b206f5-e89b-449d-9395-cd09860469d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myAccountMenu > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='myAccountMenu']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4fe754e6-8f09-4f5b-8dcf-e1d249921046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c608c991-8a13-44d1-87b8-c731e3c5ed1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MI CUENTA </value>
      <webElementGuid>38f50dd7-a591-4670-a2c0-dd4bcf0bc928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountMenu&quot;)/a[1]</value>
      <webElementGuid>71db1847-6814-45b6-b440-9bb5f8080b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='myAccountMenu']/a</value>
      <webElementGuid>96ad4a2f-926d-43db-b7c0-c748e44468e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MI CUENTA')]</value>
      <webElementGuid>49914cee-2170-47c0-bd1d-796e5902e67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAVE C2P'])[1]/following::a[1]</value>
      <webElementGuid>7d037656-c979-4b83-b7aa-ad9a6a98b560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOCIONES Y PRECIOS'])[1]/following::a[2]</value>
      <webElementGuid>f28e15c8-a631-4abd-851b-7d25e23bfeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualizar Información'])[1]/preceding::a[1]</value>
      <webElementGuid>96801695-dbf3-4330-bf48-27bb94ffb033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[1]/preceding::a[2]</value>
      <webElementGuid>79e02ef0-3ce2-43fe-90fd-8a12bed894e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MI CUENTA']/parent::*</value>
      <webElementGuid>cc77dbcc-cca6-4b63-97ef-1cee69026a13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>118eb012-bd0b-4deb-a15e-bac765fac3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>3b972f3d-3130-4f48-b441-b78360a595df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'MI CUENTA ' or . = 'MI CUENTA ')]</value>
      <webElementGuid>790766e3-d68c-445d-ab36-3bdd7295601f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
