<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enviar</name>
   <tag></tag>
   <elementGuidId>9ed6ad33-0131-4585-9c54-e90566b63087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_cl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_cl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0db901e2-3b57-46d9-be97-f3d41f407bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cfa4ed52-47a4-47b9-96e1-d3e610368144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_cl</value>
      <webElementGuid>45429cbb-bf5b-492e-998a-b85058332d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: return validFormPassword();</value>
      <webElementGuid>cf321bdd-631b-4c6d-a581-ca8b752d2681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enviar</value>
      <webElementGuid>8eefc4dc-4d52-45e8-b84a-748dbd8ba4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_cl&quot;)</value>
      <webElementGuid>a2ce8372-a9c8-4a55-8b98-cb054d3a46e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_cl']</value>
      <webElementGuid>45cc6ee5-f712-42fd-8f2a-f41b0676506b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-8948']/div[2]/button</value>
      <webElementGuid>958ab5e6-e8dc-447a-8775-d95e2ed9b068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*REPETIR CONTRASEÑA'])[1]/following::button[1]</value>
      <webElementGuid>59ccb7eb-42e9-4133-9b2b-acb3e45b11e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*CONTRASEÑA'])[1]/following::button[1]</value>
      <webElementGuid>63a614af-9540-43da-9d70-883d7212b081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFICACIONES'])[2]/preceding::button[1]</value>
      <webElementGuid>c77cd6f9-6c42-43c5-8e67-e916371c63c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar'])[4]/preceding::button[1]</value>
      <webElementGuid>f731c9e6-1bcb-480c-8f74-488b68721ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>d0af1bba-33b9-4789-9423-3fec5ce4ac0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btn_cl' and (text() = 'Enviar' or . = 'Enviar')]</value>
      <webElementGuid>f2e24a1e-cc9b-41e0-b7c6-9f4de8d12543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
