<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_CONTRASEA</name>
   <tag></tag>
   <elementGuidId>7eb611a4-9930-4f6b-9a33-697a8c33be3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#panel-8948 > h3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='panel-8948']/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>339d1449-0e58-45aa-b402-7274ef7e0d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                CONTRASEÑA
                            </value>
      <webElementGuid>efa24d84-c3ff-4320-98d7-aa5bfd072956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-8948&quot;)/h3[1]</value>
      <webElementGuid>daef29ec-d286-42c5-a7eb-cc1825e86291</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-8948']/h3</value>
      <webElementGuid>905b1f25-f6a9-467c-9bb7-7d6b82211d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar'])[2]/following::h3[1]</value>
      <webElementGuid>b8f5604b-e366-4549-943a-af5762202dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*CÉDULA'])[1]/following::h3[1]</value>
      <webElementGuid>f70ede83-9ab3-434f-a5f7-5e96e5282662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*CONTRASEÑA'])[1]/preceding::h3[1]</value>
      <webElementGuid>74724226-d59b-4872-ac8a-0827ff643c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*REPETIR CONTRASEÑA'])[1]/preceding::h3[1]</value>
      <webElementGuid>82af0286-67ff-4e87-a56e-e70dc39c1f23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h3</value>
      <webElementGuid>1f8cf33a-b806-452c-ab42-4b3a75a85736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = '
                                CONTRASEÑA
                            ' or . = '
                                CONTRASEÑA
                            ')]</value>
      <webElementGuid>89e1a63a-1781-4e40-9574-5189df8c9452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
