<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REPETIR CONTRASEA_PasswordComparation</name>
   <tag></tag>
   <elementGuidId>a34117cd-bf09-490f-aaf5-256577d354e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PasswordComparation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PasswordComparation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0576116d-dba5-464f-8e17-d55949fac216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_right</value>
      <webElementGuid>6a03cae9-64f7-4bc9-b926-facf4c517d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c928ab02-1020-4511-952e-6f6f823477df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>Las contraseñas no concuerdan</value>
      <webElementGuid>e7120faf-ea1f-422e-8e64-63e89248f326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.Password</value>
      <webElementGuid>172941f2-3792-47fc-bcd9-d5b4b947dce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Campo Requerido</value>
      <webElementGuid>7569d5b3-30bc-4c1b-8119-3780d1b60457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PasswordComparation</value>
      <webElementGuid>23293b1f-554c-4d91-9a66-e8435140dbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PasswordComparation</value>
      <webElementGuid>30647804-e77f-4420-a341-638fd913a3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>13550f0e-6f58-49cf-9259-d490bb8963dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>17856460</value>
      <webElementGuid>044f1c5d-1bb7-4964-b0b7-ebac96c9b5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasswordComparation&quot;)</value>
      <webElementGuid>b92b460c-b43c-4869-a30a-dcb66edad7e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PasswordComparation']</value>
      <webElementGuid>cc794206-1191-4a9f-b8e7-a490c5284ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-8948']/div/div[2]/div/div/input</value>
      <webElementGuid>115635de-6536-499a-8543-f63839fb94a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>14842087-662d-401b-862f-bc1a78e41042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PasswordComparation' and @name = 'PasswordComparation' and @type = 'password']</value>
      <webElementGuid>a7635a86-9471-45d3-aa61-5d675a5203ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
