<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Zack Market</name>
   <tag></tag>
   <elementGuidId>3efb939b-0d7a-423f-bb02-f298e843374b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.header_logo__T7Iva</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f7c2f064-5198-42eb-baf6-18fdbb0f4eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_logo__T7Iva</value>
      <webElementGuid>5aa4fc85-56ba-42ea-9bde-1c3f15ee82bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Zack Market</value>
      <webElementGuid>bbe281d4-b30f-4afd-a768-721bcf4ce3d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;productOverview_outbox__1y4XD&quot;]/div[@class=&quot;header_outbox__3eyFu&quot;]/div[@class=&quot;header_content__7Jk3i&quot;]/div[@class=&quot;header_left__2JCq6&quot;]/div[@class=&quot;header_logo__T7Iva&quot;]</value>
      <webElementGuid>bc5c4d59-5551-46f2-8889-6c1f0af5f1fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>ef81aa99-6ca0-4320-bab6-1fc9d7729fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Products'])[1]/preceding::div[8]</value>
      <webElementGuid>2ac93c7d-2c1e-4057-aac3-8a3dd5bf0a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Slim Jeans'])[1]/preceding::div[18]</value>
      <webElementGuid>6b7dd78b-da18-4776-b6df-2e7c53c01612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>e9aae393-69c1-4ef6-a5d9-6886bc6fb485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Zack Market' or . = 'Zack Market')]</value>
      <webElementGuid>64d8b171-2006-4747-8876-4c3d3fba67f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
