<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FILTERSORDERA</name>
   <tag></tag>
   <elementGuidId>fc6fb503-27d2-4395-a7fe-26be4958b87b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.filter_box__1bW3P</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58f5b421-14b0-47fb-b17e-75ed691f52d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter_box__1bW3P</value>
      <webElementGuid>239bca5b-5dd5-4462-91fc-bafe34ffde14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FILTERSORDERAscendingDescendingDEPARTMENTMenWomenPRICELess Than $29$29 - $39$39 - $49$49 - $89Greater Than $89Clear All</value>
      <webElementGuid>ee728536-8d38-4c85-87dd-57cface62aa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1-m91&quot;]/div[@class=&quot;dashboard_box__3yhj7&quot;]/div[@class=&quot;dashboard_filter__1u2Cj&quot;]/div[1]/div[@class=&quot;filter_outbox__1IMbW&quot;]/div[@class=&quot;filter_box__1bW3P&quot;]</value>
      <webElementGuid>772b14d8-0b50-4f12-a526-b74b4f8bb689</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div</value>
      <webElementGuid>6ac703a6-8bdc-48bd-b000-95142cfef7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Products'])[1]/following::div[11]</value>
      <webElementGuid>f27fe526-1aee-4202-b0ae-f87589680dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Market'])[2]/following::div[21]</value>
      <webElementGuid>5cb86905-8263-4e9a-8b48-de3046638be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>088748cc-f2db-4719-a998-36defe021909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FILTERSORDERAscendingDescendingDEPARTMENTMenWomenPRICELess Than $29$29 - $39$39 - $49$49 - $89Greater Than $89Clear All' or . = 'FILTERSORDERAscendingDescendingDEPARTMENTMenWomenPRICELess Than $29$29 - $39$39 - $49$49 - $89Greater Than $89Clear All')]</value>
      <webElementGuid>48e3d33c-586f-4737-a361-aa49983f04c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
