<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CopyrighT</name>
   <tag></tag>
   <elementGuidId>b4306929-5977-4a31-a1b3-04a6319cf462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.footer_outbox__1pdRu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f08395ca-b9ea-43a7-bf3d-4c3335c46cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>footer_outbox__1pdRu</value>
      <webElementGuid>91f9059a-8a2d-41c0-9eaa-7cda5c95987b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CopyrighT © 2021 Katalon LLC. All rights reserved.</value>
      <webElementGuid>c39fe1ab-0934-48c9-8464-11eecda52dff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1-m91&quot;]/div[@class=&quot;footer_outbox__1pdRu&quot;]</value>
      <webElementGuid>2c99011e-1139-45db-a325-bb69aa749ab2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[3]</value>
      <webElementGuid>6a2e0712-45d1-480b-822e-d1e05e2758ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$79.99 CAD'])[3]/following::div[1]</value>
      <webElementGuid>024541e6-0e93-4046-954f-56be0a58acbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belted Plaid Blazer'])[1]/following::div[3]</value>
      <webElementGuid>78a2f44e-1a63-4a16-946b-d80654bc4f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CopyrighT © 2021 Katalon LLC. All rights reserved.']/parent::*</value>
      <webElementGuid>6c0db246-f06a-443e-8347-e92999b245fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>02f7eba2-cfcf-4a5b-ad79-3133ff19b21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CopyrighT © 2021 Katalon LLC. All rights reserved.' or . = 'CopyrighT © 2021 Katalon LLC. All rights reserved.')]</value>
      <webElementGuid>c7bc12be-9ba2-4a3a-9d9f-469c275400e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
