<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Full nameEmail</name>
   <tag></tag>
   <elementGuidId>a63fe284-49f1-430d-8a63-4b91425a0a15</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.base_outbox__v79b7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2487d59f-02e4-4454-9072-2de6484c33ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base_outbox__v79b7</value>
      <webElementGuid>4711db2d-4828-42dd-ae39-cb82f3300d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Full nameEmailPasswordVerify passwordDo you have an account? Sign In</value>
      <webElementGuid>a625c8cc-adf5-4e40-9c38-a5fd66b87abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;loginsignin_outbox__igIjJ&quot;]/div[@class=&quot;loginsignin_box__2rRZG&quot;]/div[@class=&quot;base_outbox__v79b7&quot;]</value>
      <webElementGuid>1c4ef3ff-536c-4784-9f17-d0ff0899ca4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div</value>
      <webElementGuid>d50e7e46-865f-4731-8f56-ed681fc20207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>ca9b2c1a-5e1f-4523-bec0-22ff25b07f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Full nameEmailPasswordVerify passwordDo you have an account? Sign In' or . = 'Full nameEmailPasswordVerify passwordDo you have an account? Sign In')]</value>
      <webElementGuid>daa7d251-dcdc-4425-ae1d-d2f63bd32c13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
