<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EmailRequired</name>
   <tag></tag>
   <elementGuidId>5158c412-a6cc-4d4e-bf4b-0074e29ba5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.base_outbox__v79b7</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>129e24ce-2eec-4678-854b-13109479432e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base_outbox__v79b7</value>
      <webElementGuid>896067b7-2ca6-409b-8436-68010e67660a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EmailRequiredPasswordRequiredDon't you have an account? Sign Up</value>
      <webElementGuid>1986d3c0-806f-4712-9ca3-e2a333e5862b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;loginsignin_outbox__igIjJ&quot;]/div[@class=&quot;loginsignin_box__2rRZG&quot;]/div[@class=&quot;base_outbox__v79b7&quot;]</value>
      <webElementGuid>60782e4e-5e16-44b5-b258-5a19f09453d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div</value>
      <webElementGuid>85b45cd6-c1d7-431a-be91-76c0b552290f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div</value>
      <webElementGuid>3e11aa68-e089-4ffd-99df-c1c35822cfd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;EmailRequiredPasswordRequiredDon&quot; , &quot;'&quot; , &quot;t you have an account? Sign Up&quot;) or . = concat(&quot;EmailRequiredPasswordRequiredDon&quot; , &quot;'&quot; , &quot;t you have an account? Sign Up&quot;))]</value>
      <webElementGuid>ba1f3ccc-559d-486d-81ad-81d63a1b93e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
