<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Women</name>
   <tag></tag>
   <elementGuidId>88b29bfa-2dc4-4331-98c6-ff2d17284d31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.menu_tag__AhL7t</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>899e00d7-0903-4da9-9d03-af58972fb439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu_tag__AhL7t</value>
      <webElementGuid>045d1565-7de6-4ad5-aa83-88281e3929b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Women</value>
      <webElementGuid>6dc1fd3b-7b35-4c9e-ba40-38b51fbbcbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1-m91&quot;]/div[@class=&quot;header_outbox__3eyFu&quot;]/div[@class=&quot;header_content__7Jk3i&quot;]/div[@class=&quot;header_mid__3-jgP&quot;]/div[@class=&quot;menu_outbox__21_Hg&quot;]/div[@class=&quot;menu_lists__2tWro&quot;]/div[@class=&quot;menu_tag__AhL7t&quot;]</value>
      <webElementGuid>e6a31197-7c36-4e18-96b3-8bf4b8dd4b58</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>4d531b17-8abb-4b5e-8241-833e72e15bef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zack Market'])[2]/following::div[4]</value>
      <webElementGuid>fe3fb550-a21b-48d8-8940-e15475c24e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Products'])[1]/preceding::div[6]</value>
      <webElementGuid>19d50c9b-9700-4010-8ed6-3f20cff19290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILTERS'])[1]/preceding::div[13]</value>
      <webElementGuid>097a8e6a-c9d7-461d-a89d-da642336682f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>d379f27d-978a-487c-9062-7d7ae136936a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Women' or . = 'Women')]</value>
      <webElementGuid>15ba7abd-b831-4af9-a06f-f525f44cf887</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
