<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Share</name>
   <tag></tag>
   <elementGuidId>b49709aa-4a39-4fb8-8f9c-d5aa65dcef72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[16]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.slds-button.slds-button_brand.cuf-publisherShareButton.qe-textPostDesktop.MEDIUM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03539d63-67fd-4faa-b0f5-bbce958035a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6afbe1f0-697a-4ffd-a568-3e6b77596021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Click, or press Ctrl+Enter</value>
      <webElementGuid>a269d1cd-ed1d-4fd7-bafb-16507f9f7648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand cuf-publisherShareButton qe-textPostDesktop MEDIUM</value>
      <webElementGuid>161356eb-0f9c-4b72-bea5-aad15d55b256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>278:573;a</value>
      <webElementGuid>bd8e7431-34c6-4d05-a0e5-dd6f319d8e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Share</value>
      <webElementGuid>c50d5bd1-d8d9-47d6-bbfc-b1c590487b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;527:0&quot;)/div[@class=&quot;testid__publisher-quick-action-collapser  forcePublisherQuickActionCollapser&quot;]/div[3]/div[@class=&quot;baseDefault forceChatterBasePublisher forceChatterTextPostDesktop&quot;]/div[@class=&quot;forceChatterPublisherPresentationDesktop&quot;]/div[@class=&quot;container  activeState&quot;]/div[@class=&quot;slds-grid bottomBar&quot;]/div[@class=&quot;bottomBarRight slds-col--bump-left&quot;]/button[@class=&quot;slds-button slds-button_brand cuf-publisherShareButton qe-textPostDesktop MEDIUM&quot;]</value>
      <webElementGuid>e91bd5af-b432-4dba-8404-4157bcb7a1d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[16]</value>
      <webElementGuid>2d14aa55-6d0c-46b6-8174-ae5be49e4d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='527:0']/div/div[3]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>789c190e-0a90-4679-8c22-2a4fb75829ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attach up to 10 files'])[1]/following::button[1]</value>
      <webElementGuid>a62b8a4f-9ecc-418b-a6bf-4eced5975be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Followers'])[1]/following::button[2]</value>
      <webElementGuid>d007d435-003d-42df-a289-6dc4e9a401e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Feed'])[1]/preceding::button[1]</value>
      <webElementGuid>21c9d8b0-a2bd-4e96-9c1a-2cf43fa5802c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search this feed...'])[1]/preceding::button[1]</value>
      <webElementGuid>c6730318-def1-4171-8ecc-f5f4ff108012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e1988edd-2cf4-4d30-83de-607af31a8d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Click, or press Ctrl+Enter' and (text() = 'Share' or . = 'Share')]</value>
      <webElementGuid>79ace6f4-1f14-4d90-8793-852a7b91a8ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
