<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_prueba</name>
   <tag></tag>
   <elementGuidId>8b8b9ca7-0730-480f-8d00-1f88c9126a40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outerContainer']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.slds-rich-text-area__content.slds-text-color_weak.slds-grow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96b2fd22-1000-49f1-8f90-ae941ad51810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ql-editor slds-rich-text-area__content slds-text-color_weak slds-grow</value>
      <webElementGuid>c743807c-b6f3-4974-9241-fec361222055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bfc67e8b-4ecd-47fa-b188-87373fe25be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5986112c-9288-435b-8b32-4a52b171d93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Share an update...</value>
      <webElementGuid>82b6d34e-3f36-4da9-82dc-a02867b4fade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>fafc729a-a526-437d-8bec-43cef90e371a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-92:573;a</value>
      <webElementGuid>a81e4668-12bd-4179-9a32-968248374b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>prueba</value>
      <webElementGuid>5baf6d32-2907-4423-90f7-70abd4e8d79f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outerContainer&quot;)/div[@class=&quot;slds-form-element lightningInputRichText forceChatterMessageBodyInputRichTextEditor&quot;]/div[@class=&quot;slds-rich-text-editor slds-grid slds-grid_vertical slds-nowrap slds-has-focus&quot;]/div[@class=&quot;slds-rich-text-editor__textarea slds-grid ql-container&quot;]/div[@class=&quot;ql-editor slds-rich-text-area__content slds-text-color_weak slds-grow&quot;]</value>
      <webElementGuid>a86f7a81-aa3a-4811-ad52-8b58cf8da9b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outerContainer']/div/div/div/div</value>
      <webElementGuid>5031aa9e-8a23-44c0-92bf-5e22eb48ca75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share an update...'])[2]/following::div[3]</value>
      <webElementGuid>e0c0d196-f98d-41f7-86e7-ca3258887d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review the errors on this page.'])[1]/following::div[11]</value>
      <webElementGuid>9d379eca-724e-4aba-be7d-f1e928e9cfe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold'])[1]/preceding::div[2]</value>
      <webElementGuid>f7e4dad5-4765-4156-b389-c2ce99218215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italic'])[1]/preceding::div[2]</value>
      <webElementGuid>88854c61-90b8-48a9-b4cc-847de1261c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>79d4b6fb-095f-438c-af80-2581dd4772b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'prueba' or . = 'prueba')]</value>
      <webElementGuid>b5ac75a5-70dd-4b31-82db-e4b47625e305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
