<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_test</name>
   <tag></tag>
   <elementGuidId>275254b9-8a26-47b4-bdcf-48b7fc0c4aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outerContainer']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.slds-rich-text-area__content.slds-text-color_weak.slds-grow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed6bf0fd-0c20-4613-9e91-f595e2144a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ql-editor slds-rich-text-area__content slds-text-color_weak slds-grow</value>
      <webElementGuid>8e9fabe9-e77e-4c11-9c4e-121e872839a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>742707d8-0e29-45cc-a555-778f5aa1e8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac2f2670-3e90-41f8-b2da-9088413cf424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Share an update...</value>
      <webElementGuid>0d722d4f-db5e-4a26-b2a8-ee6428b83a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>bef757ee-93c2-4f79-b16c-8dd403850372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-92:573;a</value>
      <webElementGuid>81a9d07c-6f5c-4df4-86b2-aaf1f0c37384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>fb74e16a-7aaf-4d51-9a07-dd3d94fda3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outerContainer&quot;)/div[@class=&quot;slds-form-element lightningInputRichText forceChatterMessageBodyInputRichTextEditor&quot;]/div[@class=&quot;slds-rich-text-editor slds-grid slds-grid_vertical slds-nowrap slds-has-focus&quot;]/div[@class=&quot;slds-rich-text-editor__textarea slds-grid ql-container&quot;]/div[@class=&quot;ql-editor slds-rich-text-area__content slds-text-color_weak slds-grow&quot;]</value>
      <webElementGuid>2d47dd08-deb4-45b6-90f6-e551ffbcd669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outerContainer']/div/div/div/div</value>
      <webElementGuid>23942b3a-b182-4878-92b8-8e474be3cd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share an update...'])[2]/following::div[3]</value>
      <webElementGuid>f11fddb4-a6b1-42b3-a974-5a369a2fb969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review the errors on this page.'])[1]/following::div[11]</value>
      <webElementGuid>60e6764f-7b9f-4d61-87a3-90b325404d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold'])[1]/preceding::div[2]</value>
      <webElementGuid>ffb23faa-3cec-404d-8a3d-a2208dd268aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italic'])[1]/preceding::div[2]</value>
      <webElementGuid>56cf0d46-aa58-4f8c-975d-d9a94d01fabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>acfeb6fb-c5a5-4806-8c08-af792256f053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'test' or . = 'test')]</value>
      <webElementGuid>c6f7737a-cb49-4c05-a051-d43123d06302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
