<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Share an update_ql-editor ql-blank slds_65fe62</name>
   <tag></tag>
   <elementGuidId>84ff58b3-7d15-459c-a036-8e21791d0328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outerContainer']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.ql-blank.slds-rich-text-area__content.slds-text-color_weak.slds-grow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f601b37-8cc3-4a72-afc6-1a8a5f1888ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ql-editor ql-blank slds-rich-text-area__content slds-text-color_weak slds-grow</value>
      <webElementGuid>5144689c-ea48-48f4-b260-c13871de22fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8028b0d1-366b-427a-afe5-f8e946f39988</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>37bb3d4c-7717-41b6-ba70-b7c3f896a45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Share an update...</value>
      <webElementGuid>40ef6e32-6c2e-49a9-915b-e21da76a4bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>b5f90d4c-eef8-4e48-8c6c-b00f1b5d4a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>label-92:573;a</value>
      <webElementGuid>b315fadf-5276-4cc9-896e-96e768119ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outerContainer&quot;)/div[@class=&quot;slds-form-element lightningInputRichText forceChatterMessageBodyInputRichTextEditor&quot;]/div[@class=&quot;slds-rich-text-editor slds-grid slds-grid_vertical slds-nowrap slds-has-focus&quot;]/div[@class=&quot;slds-rich-text-editor__textarea slds-grid ql-container&quot;]/div[@class=&quot;ql-editor ql-blank slds-rich-text-area__content slds-text-color_weak slds-grow&quot;]</value>
      <webElementGuid>6c1a8769-4f79-49ce-8552-78d05c0b8dc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outerContainer']/div/div/div/div</value>
      <webElementGuid>92834f8d-43e8-420a-b3fc-f9c9eadbcbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share an update...'])[2]/following::div[3]</value>
      <webElementGuid>4a0102cf-b937-42f5-ba44-1a12cffa4fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review the errors on this page.'])[1]/following::div[11]</value>
      <webElementGuid>b1a951fb-313e-48e6-b587-b9cb43d4371d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold'])[1]/preceding::div[2]</value>
      <webElementGuid>250225c0-ce2f-4b5b-83bf-dfda40ecf233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italic'])[1]/preceding::div[2]</value>
      <webElementGuid>90259f21-841e-4dad-8ae0-968478a429c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>0badad92-2d2a-4454-8163-4caca8b04f2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
