<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_testt</name>
   <tag></tag>
   <elementGuidId>21b1152f-ecc5-4ff7-8f15-36629cdee36e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outerContainer']/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.slds-rich-text-area__content.slds-text-color_weak.slds-grow > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d86c3b23-0c2d-4110-a6c3-98f34c1b6a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>testt</value>
      <webElementGuid>7e98e12a-5c35-48f9-9a08-e7e18f4156f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outerContainer&quot;)/div[@class=&quot;slds-form-element lightningInputRichText forceChatterMessageBodyInputRichTextEditor&quot;]/div[@class=&quot;slds-rich-text-editor slds-grid slds-grid_vertical slds-nowrap slds-has-focus&quot;]/div[@class=&quot;slds-rich-text-editor__textarea slds-grid ql-container&quot;]/div[@class=&quot;ql-editor slds-rich-text-area__content slds-text-color_weak slds-grow&quot;]/p[1]</value>
      <webElementGuid>dd2724f7-2550-45a0-ac9e-2290dc396b7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outerContainer']/div/div/div/div/p</value>
      <webElementGuid>13b8d276-c635-4c21-aa39-30c2cd07cf37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share an update...'])[2]/following::p[1]</value>
      <webElementGuid>8b23e428-023b-4120-9b83-e208a51c09e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review the errors on this page.'])[1]/following::p[1]</value>
      <webElementGuid>f69c00b9-6397-48f9-aa46-d39079f70e39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold'])[1]/preceding::p[1]</value>
      <webElementGuid>5ca3d338-8ea5-41c8-a324-c583a3ff9a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italic'])[1]/preceding::p[1]</value>
      <webElementGuid>222163bc-a69e-4f92-bc41-deabcfdd32d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='testt']/parent::*</value>
      <webElementGuid>f0558dbf-6594-4857-af52-e4de5275a844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>fd3086a3-6408-4e99-93d3-3b114647151f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'testt' or . = 'testt')]</value>
      <webElementGuid>611aabeb-c86e-41af-a717-520a8b33524f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
