<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_test</name>
   <tag></tag>
   <elementGuidId>89305a2a-fd7b-4e54-b484-04f56f2ffa0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='outerContainer']/div/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ql-editor.slds-rich-text-area__content.slds-text-color_weak.slds-grow > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c16550bd-0b75-4933-a3e5-531f7aa82997</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>191c6396-6a2f-4b96-87cc-d80c6494de35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;outerContainer&quot;)/div[@class=&quot;slds-form-element lightningInputRichText forceChatterMessageBodyInputRichTextEditor&quot;]/div[@class=&quot;slds-rich-text-editor slds-grid slds-grid_vertical slds-nowrap slds-has-focus&quot;]/div[@class=&quot;slds-rich-text-editor__textarea slds-grid ql-container&quot;]/div[@class=&quot;ql-editor slds-rich-text-area__content slds-text-color_weak slds-grow&quot;]/p[1]</value>
      <webElementGuid>0dd52794-e720-4914-87e6-3c08af13fc7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='outerContainer']/div/div/div/div/p</value>
      <webElementGuid>d0662c11-25c0-49ba-b49d-b145d75ba29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share an update...'])[2]/following::p[1]</value>
      <webElementGuid>7f66eefc-fdef-4e7d-ba7b-20b0757000c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review the errors on this page.'])[1]/following::p[1]</value>
      <webElementGuid>22258235-ad25-47bc-a62e-c5a9d92dfcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bold'])[1]/preceding::p[1]</value>
      <webElementGuid>cffdf354-1de4-43de-8b22-8c9c03f95bec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Italic'])[1]/preceding::p[1]</value>
      <webElementGuid>9aa318f6-47aa-434d-862d-9c0216a1244b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test']/parent::*</value>
      <webElementGuid>ce12fb4e-517f-4588-b419-3f9a3763f193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/div/div/p</value>
      <webElementGuid>951205b5-5db9-4bf6-9036-4f6e1236a18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'test' or . = 'test')]</value>
      <webElementGuid>9085515d-ffd3-403d-96df-6d1f1338e236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
