<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose.Discusin de DesarrolladoresDi_3e73a8</name>
   <tag></tag>
   <elementGuidId>186276d4-b133-4df1-a725-16fb82d969dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='17:1236;a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5301de80-d70a-408b-8504-b6c18ec76472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>de4bdb41-8084-463c-a60b-15d262955f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>17:1236;a</value>
      <webElementGuid>ba8cb9e5-d702-4593-aedb-cf423ee66919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>80fe6fe8-49c5-4118-aac7-30ed9db8fb18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>35:1236;a</value>
      <webElementGuid>ed5ce5dc-079d-44af-a032-5e4c2f80117a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose...Discusión de DesarrolladoresDiscusión de QADiscusión GeneralDiscusión sobre APIs</value>
      <webElementGuid>f08a8d85-9ceb-4f32-a04f-0087acc51b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;17:1236;a&quot;)</value>
      <webElementGuid>527c03ed-3b67-44d5-b563-00ea3119a309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='17:1236;a']</value>
      <webElementGuid>3630d885-1c96-40c6-a5b4-b1c2ce7dd6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_420:1236;a']/div/div/div/div/div[3]/div/div/div/div/div/select</value>
      <webElementGuid>a2caece9-5a98-4e3d-ba93-d735d8a617d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post To'])[1]/following::select[1]</value>
      <webElementGuid>461af070-4ba9-436e-995b-30ef4a686a8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::select[1]</value>
      <webElementGuid>249e1b3b-b597-4ab0-895c-e853cffbc901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a post destination.'])[1]/preceding::select[1]</value>
      <webElementGuid>5959f97f-0741-43f6-9855-80df773ab833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::select[1]</value>
      <webElementGuid>322b6b1e-01f3-47d0-a787-21aeee0c88e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d7180b4c-2f00-41f7-858d-934c1e18eeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '17:1236;a' and (text() = 'Choose...Discusión de DesarrolladoresDiscusión de QADiscusión GeneralDiscusión sobre APIs' or . = 'Choose...Discusión de DesarrolladoresDiscusión de QADiscusión GeneralDiscusión sobre APIs')]</value>
      <webElementGuid>27dad899-9d60-4389-97ce-ccf5852dfd89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
