<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_ToMy Followers</name>
   <tag></tag>
   <elementGuidId>d6648292-e3b7-41b1-bc66-65dbe633c980</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='527:0']/div/div[3]/div/div/div/div/div[3]/div/div/div/ul</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.items</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>9bc29b6c-3d0f-43dd-bb1a-1066acc17e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>items</value>
      <webElementGuid>ca383223-4a5e-4cf4-bbf2-093a3b2086c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>15:573;a</value>
      <webElementGuid>fad96f6f-eca1-44c7-bb36-be131c3c67ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToMy Followers</value>
      <webElementGuid>eb4bd745-185b-48c6-ab90-190561582580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;527:0&quot;)/div[@class=&quot;testid__publisher-quick-action-collapser  forcePublisherQuickActionCollapser&quot;]/div[3]/div[@class=&quot;baseDefault forceChatterBasePublisher forceChatterTextPostDesktop&quot;]/div[@class=&quot;forceChatterPublisherPresentationDesktop&quot;]/div[@class=&quot;container  activeState&quot;]/div[@class=&quot;cuf-content scrollable&quot;]/div[@class=&quot;visibilitySwitcher&quot;]/div[1]/div[@class=&quot;cuf-publisherVisibility forceChatterPublisherVisibility&quot;]/div[@class=&quot;forceChatterPublisherVisibilityWrapper&quot;]/ul[@class=&quot;items&quot;]</value>
      <webElementGuid>39943a6c-a997-4a1c-adc2-9e0c3ba2488a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='527:0']/div/div[3]/div/div/div/div/div[3]/div/div/div/ul</value>
      <webElementGuid>9841d8a1-4fe8-4517-8af8-e0c3f0d89aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Topic'])[1]/following::ul[2]</value>
      <webElementGuid>01ee733e-049d-4e6c-9a1c-d81860e3e258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@Mention people and groups'])[1]/following::ul[3]</value>
      <webElementGuid>ba0c5eb6-c3cc-4c34-9fd3-d83dd0a0506b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[3]/div/div/div/div/div[3]/div/div/div/ul</value>
      <webElementGuid>4adb52fb-bde8-43c6-9f3a-009cd8f64bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//ul[(text() = 'ToMy Followers' or . = 'ToMy Followers')]</value>
      <webElementGuid>76c2e4d8-a6f1-4981-999e-0620f7af09ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
