<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Need a user name and password_username</name>
   <tag></tag>
   <elementGuidId>10b81194-c040-4374-b6e5-fc9001094dc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stripes--1251301532</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stripes--1251301532']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41a2c560-d96d-4f36-b05f-4adf538b7c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>ba8ca0cb-dbbe-4321-a866-d997d3349e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stripes--1251301532</value>
      <webElementGuid>a1164d4c-292b-4bac-be7d-e306af9e94e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3282077d-5f30-4d35-9ec9-5507115ff45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stripes--1251301532&quot;)</value>
      <webElementGuid>07ab4ab3-2782-4dac-b4c3-dc1ac6e92ed6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stripes--1251301532']</value>
      <webElementGuid>17097d28-f871-46c7-a0d6-3537b3d42d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/p[2]/input</value>
      <webElementGuid>082bf7e6-21ce-4f12-90b5-bbfcf1fb6670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>d9721d8a-f37f-4a22-8207-d1811f22c84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'username' and @id = 'stripes--1251301532' and @type = 'text']</value>
      <webElementGuid>4c282cb7-4465-44f8-82d1-5921ff33732c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
