<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FISHDOGSREPTILESCATSBIRDS</name>
   <tag></tag>
   <elementGuidId>daf08b52-a8a3-4e1b-a031-d695067229b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;account.favouriteCategoryId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='account.favouriteCategoryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f6395878-f9f9-4f2c-b09c-1d2167259423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account.favouriteCategoryId</value>
      <webElementGuid>951805c7-fa5c-45ed-bd15-1f2a14be80a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
			FISHDOGSREPTILESCATSBIRDS
		</value>
      <webElementGuid>deb14703-e2ce-4756-ac92-933e7d6c1c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Catalog&quot;)/form[1]/table[3]/tbody[1]/tr[2]/td[2]/select[1]</value>
      <webElementGuid>c3063c0f-0a22-40dc-a3cb-f7d7937644fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='account.favouriteCategoryId']</value>
      <webElementGuid>2941c6d1-2f0e-4652-878e-1836a0698771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Catalog']/form/table[3]/tbody/tr[2]/td[2]/select</value>
      <webElementGuid>bd318d5e-9387-4df8-b781-3a1f617a5dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favourite Category:'])[1]/following::select[1]</value>
      <webElementGuid>a8bdd37f-2cb4-48f1-b4d8-b0888e407b81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Preference:'])[1]/following::select[2]</value>
      <webElementGuid>5932e483-2eba-4090-8fc0-982b32a0ca4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyList'])[1]/preceding::select[1]</value>
      <webElementGuid>0ed2f512-65f7-4db1-ada7-61e5740db1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enable MyBanner'])[1]/preceding::select[1]</value>
      <webElementGuid>a1cea739-dd46-4204-acfb-679912fad2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/select</value>
      <webElementGuid>30b30b31-8b57-473a-acec-2a15ce9428a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account.favouriteCategoryId' and (text() = '
			FISHDOGSREPTILESCATSBIRDS
		' or . = '
			FISHDOGSREPTILESCATSBIRDS
		')]</value>
      <webElementGuid>cf06411c-3862-478e-9d79-be7cfcbd0de5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
