<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actualizar Informacin</name>
   <tag></tag>
   <elementGuidId>ecd4274e-8a91-4fbd-8722-03cc6e299823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.is-cuenta-menu > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountMenu-Login']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19df3c57-35af-43dc-b784-9f19644d9d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Mi_Cuenta/UpdateUser?hash=bGlzc2V5bWFtb3JhbGVzQGdtYWlsLmNvbQ==</value>
      <webElementGuid>c07f2740-918d-443b-a48f-aa428824f6b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar Información</value>
      <webElementGuid>1ea718cd-eb5a-4491-8d20-6ca764af880e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountMenu-Login&quot;)/div[@class=&quot;is-cuenta-menu&quot;]/a[1]</value>
      <webElementGuid>4fd8e79f-af56-4b8b-ae63-1544ef34b5c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountMenu-Login']/div/a</value>
      <webElementGuid>72dc86f6-174b-441b-9b04-dd91c203f491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Actualizar Información')]</value>
      <webElementGuid>f79f1994-0adb-45ae-9e90-bf52aec83dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAVE C2P'])[1]/following::a[2]</value>
      <webElementGuid>ed8d51c3-a40e-427b-adfb-ee3dfe1bc90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOCIONES Y PRECIOS'])[1]/following::a[3]</value>
      <webElementGuid>9845c107-8a4b-4338-a3e6-330329cf3027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[1]/preceding::a[1]</value>
      <webElementGuid>e5831f9a-0543-4d9d-80fa-c12b6f3ea4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finalizar Sesión'])[1]/preceding::a[3]</value>
      <webElementGuid>c1978096-ac13-4f00-a13e-437cf14fe509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actualizar Información']/parent::*</value>
      <webElementGuid>8bb785ef-21a7-4c3b-835a-cfa8fffe02a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Mi_Cuenta/UpdateUser?hash=bGlzc2V5bWFtb3JhbGVzQGdtYWlsLmNvbQ==')]</value>
      <webElementGuid>7be333f0-c015-49c0-a9f5-1752ab73ffac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>09566d6c-eb5a-4d7a-bfc3-998bcb657f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Mi_Cuenta/UpdateUser?hash=bGlzc2V5bWFtb3JhbGVzQGdtYWlsLmNvbQ==' and (text() = 'Actualizar Información' or . = 'Actualizar Información')]</value>
      <webElementGuid>a08c645e-f0cd-41b5-8f27-3a6651249645</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
