<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CONTRASEA</name>
   <tag></tag>
   <elementGuidId>99e57505-99d4-4b92-aa62-0f32b2c3ae0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabs-790603']/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c96ca739-e6c6-45a2-94a0-2fcc312f75f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#panel-8948</value>
      <webElementGuid>12284192-8314-4fde-80f1-d309048116a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e008161f-9781-4f75-bb51-fcaab204a4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTRASEÑA</value>
      <webElementGuid>209ea42e-08a5-4e1a-b75d-5b85d7e7666f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs-790603&quot;)/ul[@class=&quot;nav nav-tabs&quot;]/li[3]/a[1]</value>
      <webElementGuid>e174dfbb-7c4a-4bbe-bb0a-50fd3fae2814</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs-790603']/ul/li[3]/a</value>
      <webElementGuid>33e8e23c-cd71-4e63-8838-3dff866de42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'CONTRASEÑA')]</value>
      <webElementGuid>7d406711-953a-4097-8e87-bc4d0cb5f69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATOS PERSONALES'])[1]/following::a[1]</value>
      <webElementGuid>46230855-1d8a-4505-ae18-7f762864917a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATOS DE REGISTRO'])[1]/following::a[2]</value>
      <webElementGuid>3eada016-ae87-43ca-81e0-10005c0d42be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFICACIONES'])[1]/preceding::a[1]</value>
      <webElementGuid>5932d926-472f-418b-91fc-e3af9359ca12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATOS DE REGISTRO'])[2]/preceding::a[2]</value>
      <webElementGuid>ed122fa0-a308-4a92-adcb-86e924dd8a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTRASEÑA']/parent::*</value>
      <webElementGuid>388184d2-c067-419d-8d36-3da587ccc3b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#panel-8948')]</value>
      <webElementGuid>70bd98bd-f585-432c-939c-cec80ee3098e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li[3]/a</value>
      <webElementGuid>547be6c9-6cc0-4b42-8c8b-d9100b87da49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#panel-8948' and (text() = 'CONTRASEÑA' or . = 'CONTRASEÑA')]</value>
      <webElementGuid>c90f6b7b-904a-4cd5-afee-2892124e89c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
