<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_INICIAR SESIN</name>
   <tag></tag>
   <elementGuidId>8c90ee15-e23e-4efd-bdf6-6039a52370a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.is-cuenta-menu > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myAccountMenu-Login']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33702329-a68b-43d5-b629-649361d06d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Inicio_Sesion</value>
      <webElementGuid>6dbb61af-bd0b-4ab5-ac96-133955a46b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INICIAR SESIÓN</value>
      <webElementGuid>757e287e-b089-4fd0-a05f-c42e73921e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountMenu-Login&quot;)/div[@class=&quot;is-cuenta-menu&quot;]/a[1]</value>
      <webElementGuid>452fd3c1-0e5c-4efb-9905-40938ac6eef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myAccountMenu-Login']/div/a</value>
      <webElementGuid>53f88da5-e173-42a9-8c22-13a7d479f3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'INICIAR SESIÓN')]</value>
      <webElementGuid>ab26dca5-ba33-49af-bd76-ce3159c3212c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAVE C2P'])[1]/following::a[2]</value>
      <webElementGuid>cdba95d1-d933-4b9d-8862-98210eb1cda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOCIONES Y PRECIOS'])[1]/following::a[3]</value>
      <webElementGuid>1d5c832d-41d9-4e7c-a3a8-0f5ef2c47c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGISTRARSE'])[1]/preceding::a[1]</value>
      <webElementGuid>6f4f6b95-5615-4f0b-9b63-d6bf704aa2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTACTO'])[1]/preceding::a[2]</value>
      <webElementGuid>6bf68455-f150-4275-a99c-36f51d8b6385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INICIAR SESIÓN']/parent::*</value>
      <webElementGuid>8907750f-181b-4073-9e1a-68e3d849b0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Inicio_Sesion')]</value>
      <webElementGuid>7f4f82ca-392c-43c2-a8f8-fb33e119bc5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>51c55f8b-cb29-4ff9-ae75-24816ee74cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Inicio_Sesion' and (text() = 'INICIAR SESIÓN' or . = 'INICIAR SESIÓN')]</value>
      <webElementGuid>baaf5721-e048-4507-b554-865879b69532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
