<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_MI CUENTA</name>
   <tag></tag>
   <elementGuidId>e45a555a-4635-4bb1-a4b1-5e5ccc3abf8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myAccountMenu > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='myAccountMenu']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ab47a06-5503-4bee-b5a9-02b66fe81684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5a991775-c696-40cf-9769-58544d30298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MI CUENTA </value>
      <webElementGuid>8bd18217-3b84-44b5-b9ba-ddf6dca05e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myAccountMenu&quot;)/a[1]</value>
      <webElementGuid>06b18917-1558-4776-8525-3c5af9edf795</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='myAccountMenu']/a</value>
      <webElementGuid>7fb93b0d-b9ca-4500-8120-a78edf5f1e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'MI CUENTA')]</value>
      <webElementGuid>669f9302-cae7-45b5-929c-3b2719ec18a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLAVE C2P'])[1]/following::a[1]</value>
      <webElementGuid>ba9e3ddc-4f93-4680-a4de-e723dd8389b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROMOCIONES Y PRECIOS'])[1]/following::a[2]</value>
      <webElementGuid>47675168-60ab-407f-a1ec-89f969855230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualizar Información'])[1]/preceding::a[1]</value>
      <webElementGuid>0e7e5bee-2ab0-4219-9022-ef5b18ea023c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mis Compras'])[1]/preceding::a[2]</value>
      <webElementGuid>398db42a-8be9-491f-9a5e-91eda57857bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MI CUENTA']/parent::*</value>
      <webElementGuid>b612fc03-8e05-40e1-a11a-ba0b786a1306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>b8468c3b-86de-4d99-badc-019902451e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>3b6e5831-313b-4283-be45-ee248b93c6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'MI CUENTA ' or . = 'MI CUENTA ')]</value>
      <webElementGuid>83456000-b2a0-41ef-a21b-ad928c806ca1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
