<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enviar</name>
   <tag></tag>
   <elementGuidId>c3127db0-8609-4bb6-999a-41cd41e4f727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_cl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_cl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8f607c32-2d1d-44af-a247-6811cf5070b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>18030eda-cd6c-43c6-8f42-75e17f7025ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_cl</value>
      <webElementGuid>4b864105-4f4d-424d-9813-5184394234f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript: return validFormPassword();</value>
      <webElementGuid>03d69bba-89c6-431e-ba9a-b002bd595d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enviar</value>
      <webElementGuid>3632291e-92bf-4639-96d0-36fd21e7f614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_cl&quot;)</value>
      <webElementGuid>a1fcdc04-3ae6-4cac-a9e5-57193bfac458</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_cl']</value>
      <webElementGuid>eb31bff8-32b7-422b-8602-8c075d970ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-8948']/div[2]/button</value>
      <webElementGuid>fc1777fd-5d42-4c02-958a-7c1e2cbf4201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*REPETIR CONTRASEÑA'])[1]/following::button[1]</value>
      <webElementGuid>76a31ec8-69f4-43c0-93c2-9ee2bd7cb151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*CONTRASEÑA'])[1]/following::button[1]</value>
      <webElementGuid>ff0d6f33-4d27-4c8c-beda-d3ccd805c9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOTIFICACIONES'])[2]/preceding::button[1]</value>
      <webElementGuid>3e7ecda5-4bf3-45b6-a101-2f5a66c1436a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enviar'])[4]/preceding::button[1]</value>
      <webElementGuid>77846724-eeba-4d10-96e6-6da2558caa1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>199825e1-a982-49ff-8dff-b2b765640bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btn_cl' and (text() = 'Enviar' or . = 'Enviar')]</value>
      <webElementGuid>562bc2ad-bf6a-445e-a56e-5d86420f1aa2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
