<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_REPETIR CONTRASEA_PasswordComparation</name>
   <tag></tag>
   <elementGuidId>c9aeb5c0-3aac-45c6-b780-eb297a17cf87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PasswordComparation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PasswordComparation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d08611e6-3d1d-4a32-aa57-5fe46ccc7d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_right</value>
      <webElementGuid>a9bdb902-3366-441e-b5f1-b3ee186c75de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>73e665d4-8273-44ff-beee-c7e3a7d5ba84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto</name>
      <type>Main</type>
      <value>Las contraseñas no concuerdan</value>
      <webElementGuid>4cde6560-c7ee-4ce5-9ad5-0de507ac399d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-equalto-other</name>
      <type>Main</type>
      <value>*.Password</value>
      <webElementGuid>6a9eb806-278c-4bc8-8b9c-c69205c8439b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Campo Requerido</value>
      <webElementGuid>dd69274d-a703-42a4-b0fd-12239adcd8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PasswordComparation</value>
      <webElementGuid>349c09ff-4e0a-4101-9962-4e44c20da7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PasswordComparation</value>
      <webElementGuid>2547a829-66f0-44cd-9b1f-669284498653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ac1238e7-7984-4b6d-9485-5b2a2a706a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>DemoTest</value>
      <webElementGuid>3ca68d1a-28a6-4777-94e1-a8d459ac5dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PasswordComparation&quot;)</value>
      <webElementGuid>949dae6f-de0e-4553-b3c9-241fce6e2f6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PasswordComparation']</value>
      <webElementGuid>0c3405a9-a0dd-4202-94fe-18a187b715b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-8948']/div/div[2]/div/div/input</value>
      <webElementGuid>012272c6-9fc8-4fb8-bd94-ee80cab00293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/input</value>
      <webElementGuid>fee82789-be42-4fab-b4c9-f637cc859bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PasswordComparation' and @name = 'PasswordComparation' and @type = 'password']</value>
      <webElementGuid>ab732e57-2545-4898-b687-2033bedc2e4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
